## First Steps 🛸

Hi! it's me, **Nachito**, taking my first baby steps in Python. Let's learn and enjoy together! 😉

As my previous experience in matlab, I will be using this enviroment mainly to solve mathematical problems and cast simulations.

All my "objects" will be treated as vectors or matrices, so it would be nice to start by defining some of this elements.

**For example:**
let's define an escalar, a vector and a matrix, such as:

$$ a = n \quad n  \in \mathbb{R}$$


$$
\mathbf{v} = 
 \begin{bmatrix}
    v_{0} & v_{1} & v_{2} \\
 \end{bmatrix}
$$


$$ \mathbf{A} = 
 \begin{bmatrix}
    a_{00} & a_{01} & a_{02} \\
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23}
 \end{bmatrix}
$$ 

**NOTE: We are not using the traditional text book index for the matrices and the vectors, we're using the ones the code would use.**

First, we import some libraries. They may come in handy in the future:

In [1]:
import numpy as np
from matplotlib import pyplot as plt
from scipy import integrate

Now, we write below in a "code" type cell

In [2]:
a = 1
v = [1,0,1]
A = [[1,2,3],
     [4,5,6],
     [7,8,9]]

Let's print some of this values to familiarize whit the visualization a litte

In [3]:
print("Matrix A = ",A)
print("vector v = ",v)

Matrix A =  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
vector v =  [1, 0, 1]


Now I want to create an array matrix:

In [4]:
Aarray = [[[1,2]],[[3,4]],[[5,6]],[[7,8]]]

In [5]:
print("first element = ",Aarray[0])
print("last element = ",Aarray[1])

first element =  [[1, 2]]
last element =  [[3, 4]]


In [ ]:
## it did not worked as I wanted to
## what I wanted was: A[0][0] = [1,2]
## Those are comments!

Until now, we've been creating this vectors as nested lists. All the mathematical operation between this objects are defined on a library called numpy

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 2], [2, 2]])
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

Now let's try add and multiply this elements

In [11]:
C = A + B
print("sum:",C)
D = 2 * A
print("escalar mult:\n",D)
C = A.dot(B)
print("matrix mult:n",C)
print("\na:", a)
print("b:", b)
c = a.dot(b)
print("a.dot(b):", c)

sum: [[3 4]
 [5 6]]
escalar mult:
 [[2 4]
 [6 8]]
matrix mult:n [[ 6  6]
 [14 14]]

a: [1 2 3]
b: [4 5 6]
a.dot(b): 32


Ok, so far so bueno. Let's go with something else (I want to use it in my baby Kyber example):

A matrix in which element is a vector...

In [38]:
import numpy as np

# Create a 3-dimensional vector array with shape (2, 2, 4)
vector_array = np.array([[[1, 1, 1, 1],
                          [5, 6, 7, 8]],
                         [[13, 14, 15, 16],
                          [21, 22, 23, 24]]])
vector_array2 = np.array([[[1, 1, 1, 1],
                          [5, 6, 7, 8]],
                         [[13, 14, 15, 16],
                          [21, 22, 23, 24]]])

# Accessing elements in the vector array
print(vector_array[0, 1, 2]) # Output: 7
print(vector_array[1, 1, 0]) # Output: 21

# https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-465 
c =vector_array[0][0] @ vector_array2[0][0] # what is the @ operator? It is the Matrix Multiplication (requires pythom >= 3.5 )
print(c)
print("vector_array.shape: ", vector_array.shape)

7
21
4
vector_array.shape:  (2, 2, 4)


In [17]:
vector_array[0][1]
# This worked as I expected!

array([5, 6, 7, 8])

## Step 2: 'Alea iacta est' 🎲
In this previous step we have set the bases to implement some of the most common operations, now let's add some randomness.

We start we something simple, an integer uniform distribution. 

Supose we have a set of ten values

$$
\newcommand{\set}[1]{\{ #1 \}}
S = \set{0, 1, 2, 3, 4, 5, 6, 7 ,8, 9}
$$

An unformly distributed integer random variable is represented as:

$$
X \stackrel{}{\sim} U[0,9]
$$

This means

$$
\mathbf{P}(X = x) = \frac{1}{n} \qquad x \in S
$$

being $n$ the amount of elemens in $S$



In [30]:
# Generate a vector of 4 integer uniform samples between 0 and 9
vector = np.random.randint(low=0, high=10, size=4)

# Print the generated vector
print(vector)
vector_array[0][0] = vector
print(vector_array[0][0])

[9 6 8 7]
[9 6 8 7]


As you may know, the result of a Bernoulli experiment can be either **success (1 - one)** or **failure (0 - zero)**. A random variable whichs represent this experiment is following a distribution called Bernolli distribution. The probability of success is ussually called "p":

$$
X \stackrel{}{\sim} Ber(p)
$$
This means
$$
\newcommand{\set}[1]{\{ #1 \}}
\mathbf{P}(X = x) = p \qquad x \in \set{0, 1}
$$
Here is an example of a guy fliping a equiprobable coin 10 times


In [31]:
# Generate a vector of 10 Bernoulli trials
n, p = 1, 0.5
s = np.random.binomial(n, p, 10)
print(s)

[0 1 0 0 0 0 0 1 0 1]


Another ineresting distribution is the Binomial distribuition. Samples from this distribution summarize the amount of successes (ones) we obtained have in $n$ Bernoulli experiments with probability $p$. 
Here's an example:

In [33]:
n, p = 10, .5  # number of trials, probability of each trial
s = np.random.binomial(n, p, 10)
# number of succeses when flipping a coin 10 times, tested 10 times.
print(s)

s_hat = n * np.ones(n, dtype=int)
print(s_hat)
s_hat = s_hat - s
print(s_hat)

[3 8 7 5 6 5 5 6 4 7]
[10 10 10 10 10 10 10 10 10 10]
[7 2 3 5 4 5 5 4 6 3]


Finaly we give an example of a Centered Binomial Distribution (CBN). It consist in $n$ + $k$ Bernoulli trails, we count the number of successes in the first $n$ trials and substrac the number of failures in the last $k$ trials. The probability $p$ is fixed for both sets of trials. Here's an example, we consider $n$ = $k$.
RN : Attentino, the CBN is  a B(n,p) where we substract for each result -n.p (the mean)


In [39]:
n, p = 10, .5  # number of trials, probability of each trial
l = 4 # array lenght
a = np.random.binomial(n, p, l)
b = np.random.binomial(n, p, l)

print(a)
print(b)
s = np.zeros(l, dtype=int)
for i in range(l):
    s[i] = a[i] + b[i] - 10
print(s)

[6 7 7 5]
[6 6 3 6]
[2 3 0 1]


We briefly introduce this distributions because we are going to use them in our **Baby Kyber** example (comming soon...).

If you want to now about expectation,variance and/or operations between this random variables you can read any book about basic probability or ask ChatGPT. 👾

# Appendix : Testing some additional functions

In [35]:
#testing how the convolution function works here in Python
np.convolve([2, 1, 2,2,1,0], [0, 1, 2,])

array([0, 2, 5, 4, 6, 5, 2, 0])

In [36]:
# Testing how the modulo operator works here in Python:
a = np.array([12, 13, 15, 4])
b = np.remainder(a,12)
b_mod = a % 12
print(b)
print(b_mod)

[0 1 3 4]
[0 1 3 4]


In [37]:
# Playing with the function "polydiv"
a = np.array([2, 1, 2])
b = np.array([0, 1, 2])
c = np.convolve(a,b)

poly_mod_cyclic = np.array([1, 0, 0, -1])
poly_mod_negacyclic = np.array([1,0, 0, 0, 1])
[quotient, reminder_cyclic] = np.polydiv(c, poly_mod_cyclic)
[quotient, reminder_negacyclic] = np.polydiv(c, poly_mod_negacyclic)

print("Convolution:",c)
print("Reminder Cyclic:", reminder_cyclic)
print("Reminder Nega-Cyclic:", reminder_negacyclic)

Convolution: [0 2 5 4 4]
Reminder Cyclic: [5. 4. 6.]
Reminder Nega-Cyclic: [2. 5. 4. 4.]


We will use those last 3 cells to multiply polynomials in this example. Real Kyber implementations use the Number Theoretic Transform (NTT) to multiply elements in $R_q$ (see Appendix).